import type { TimerConfig } from "@/types";

export const defaultConfig: TimerConfig = {
  type: "countdown",
  target: "main",
  autostart: true,
  showMs: false,
  font: "Barlow Condensed",
  fontUrl: "",
  color: "#F4F8FF",
  bg: "transparent",
  size: 140,
  shadow: true,
  theme: "steel",
  renderer: "classic",
  anim: true,
  motion: "normal",
  segmentGlow: true,
  flipSpeed: "normal",
  ringThickness: 12,
  ringTicks: false,
  flapSpeed: "normal",
  showInfo: false,
  infoText: "",
  infoPosition: "tr",
  infoStyle: "chip",
  duration: 300,
  endMode: "stop",
  start: 0,
  work: 1500,
  rest: 300,
  rounds: 4,
  autoNext: true,
  finalMode: "stop"
};
